FROM golang:1.22

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

ENTRYPOINT go build -v -o /usr/local/bin/app/ ./... 

# docker run --rm -v "$PWD/build":/usr/local/bin/app/ -w /usr/src/app gobuild 