httpClient:
  host: "localhost"
  port: ":8080"

postgresConnect:
  host: "localhost"
  port: ":5432"
  user: "user1"
  password: "changeme"
  dbname: "tododb"


kafka:
  brockers:
    - "localhost:9095"
    - "localhost:9096"
    - "localhost:9097"
  topic: "message"