httpClient:
  host: "app"
  port: "8081"

postgresConnect:
  host: "postgres"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "messages"

kafka:
  brockers:
    - "kafka:9092"
    # - "kafka-2:9092"
    # - "kafka-3:9092"
  topic: "message"